### ISSUE TITLE
Sometimes the final randomly selected entry does not stay highlighted

### ISSUE THREAD

**Issue by danny-don** [danny-don/option-picker#1]
Sometimes the final randomly selected entry does not stay highlighted meaning that the user may miss which entry the option picker has picked

**Comment by EmmaDawsonDev** [comment]
Can you assign me to this issue please?

**Comment by danny-don** [comment]
Done!

**Comment by EmmaDawsonDev** [comment]
Thanks :) I'll let you know how I get on!
