### ISSUE TITLE
The button that picks an option only works once

### ISSUE THREAD

**Issue by danny-don** [danny-don/option-picker#2]
The button that picks an option only works once. This means if you want it to pick a different option, you need to reload the page but then you will lose everything you entered in the to-do list. It would be better if the button worked more than once

**Comment by manikaaggarwal** [comment]
I can work. Please assign

**Comment by manikaaggarwal** [comment]
I just checked, for me it seems to be working more than once. And even after adding additional options to the list.

**Comment by danny-don** [comment]
Oh that's strange. What browser are you using? I'm using Firefox

**Comment by manikaaggarwal** [comment]
Chrome

**Comment by danny-don** [comment]
Anyone willing to try in Firefox?

**Comment by EmmaDawsonDev** [comment]
I can replicate this problem in firefox and chrome
